spring.application.name=Aula20260819-1

# spring.jpa.defer-datasource-initialization=true

# DataSource Configuration
# spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/loja
spring.datasource.url=jdbc:postgresql://pdbbackn:5432/loja
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true